---
- name: Install roles
  community.general.ansible_galaxy_install:
    type: role
    name: '{{ item }}'
  become: false
  loop:
    - xbufu.ansible
    - xbufu.packer
    - xbufu.terraform
    - xbufu.docker
    - xbufu.base_vm
