---
- name: Install collections
  community.general.ansible_galaxy_install:
    type: collection
    name: '{{ item }}'
  become: false
  loop:
    - microsoft.ad
    - community.windows
    - ansible.windows
    - pfsensible.core
    - community.docker
    - community.general
    - ansible.posix
    - community.vmware
