---
# - name: Install Ansible
#   community.general.pipx:
#     name: ansible
#     install_apps: true
#     install_deps: true
#   become: false

- name: Install Ansible
  ansible.builtin.pip:
    name: ansible
    extra_args: --user
  become: false

- name: Install Ansible Lint
  ansible.builtin.pip:
    name: ansible-lint
    extra_args: --user
  become: false
