---
- name: Get users home directory
  ansible.builtin.command: echo ~{{ ansible_env.SUDO_USER | default("root") }}
  register: output

- name: Save user home to variable
  ansible.builtin.set_fact:
    user_home: "{{ output.stdout }}"

- name: Install Ansible
  ansible.builtin.include_tasks: install_ansible.yml

- name: Install additional dependencies
  ansible.builtin.include_tasks: install_additional_dependencies.yml

- name: Fix ansible-galaxy path
  ansible.builtin.include_tasks: galaxy_path_fix.yml
  when: ansible_os_family == "Debian"

- name: Install collections
  ansible.builtin.include_tasks: install_collections.yml

- name: Install roles
  ansible.builtin.include_tasks: install_roles.yml
