---
- name: Make sure Python3 and pip3 are installed
  ansible.builtin.package:
    name:
      - python3-full
      - python3-pip
    state: present

# - name: Get users home directory
#   ansible.builtin.command: echo ~{{ ansible_env.SUDO_USER }}
#   register: output

# - name: Save user home to variable
#   ansible.builtin.set_fact:
#     user_home: "{{ output.stdout }}"

- name: Ensure Python binary directory is in PATH
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "\n#Python PATH\nexport PATH=$PATH:$HOME/.local/bin\n"
    state: present
    create: true
    insertafter: EOF
    mode: '0644'
